/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 my_neighbour_totoro.glb --transform 
Files: my_neighbour_totoro.glb [93.69MB] > /Users/albertkadyrov/Projects/three/src/assets/my_neighbour_totoro-transformed.glb [4.38MB] (95%)
Author: Hollie Rose (https://sketchfab.com/HollyRose)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/my-neighbour-totoro-9f62614463724725bd97fad6bd7d13c6
Title: My Neighbour Totoro
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import { Group, Object3DEventMap } from 'three';

interface TotoroProps {}

export function Totoro(props: TotoroProps) {
  const { nodes, materials } = useGLTF('./src/assets/my_neighbour_totoro-transformed.glb');
  const modelRef = useRef<Group<Object3DEventMap>>(null);

  useFrame((state) => {
    if (modelRef.current) {
      modelRef.current.position.y = -2.3 + Math.sin(state.clock.elapsedTime) * 0.04;
    }
  });

  return (
    <group {...props} ref={modelRef} dispose={null} position={[0, -2.7, 0]} scale={[0.06, 0.06, 0.06]}>
      {/* @ts-ignore */}
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} scale={0.368} />
    </group>
  );
}

useGLTF.preload('./src/assets/my_neighbour_totoro-transformed.glb');
