/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 totoro2.glb --transform 
Files: totoro2.glb [300.02KB] > /Users/albertkadyrov/Projects/three/src/assets/totoro2-transformed.glb [45.24KB] (85%)
Author: Linda Loukonen (https://sketchfab.com/lindaloukonen)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/totoro-6d326fe31fe14f68baede868084fef2e
Title: Totoro
*/

import { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { Group, Object3DEventMap } from 'three';
import { useFrame } from '@react-three/fiber';

interface TotoroProps {}

export function Totoro2 (props: TotoroProps) {
  const { nodes, materials } = useGLTF('./src/assets/totoro2-transformed.glb');
  const modelRef = useRef<Group<Object3DEventMap>>(null);

  useFrame((state) => {
    if (modelRef.current) {
      modelRef.current.position.y = -3 + Math.sin(state.clock.elapsedTime) * 0.02;
    }
  });
  
  return (
    <group {...props} ref={modelRef} dispose={null} position={[-5, 0.5, -1]} scale={[0.9, 0.9, 0.9]} rotation={[0, 2, 0]}>
      {/* @ts-ignore */}
      <mesh geometry={nodes.totoro1_pCube1_lambert2_0.geometry} material={materials.lambert2} scale={0.057} />
    </group>
  );
}

useGLTF.preload('./src/assets/totoro2-transformed.glb');
