/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 my_neighbour_totoro.glb --transform 
Files: my_neighbour_totoro.glb [93.69MB] > /Users/albertkadyrov/Projects/three/src/assets/my_neighbour_totoro-transformed.glb [4.38MB] (95%)
Author: Hollie Rose (https://sketchfab.com/HollyRose)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/my-neighbour-totoro-9f62614463724725bd97fad6bd7d13c6
Title: My Neighbour Totoro
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/my_neighbour_totoro-transformed.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_4.geometry} material={materials['Material.005']} scale={0.368} />
    </group>
  )
}

useGLTF.preload('/my_neighbour_totoro-transformed.glb')
